---
galaxy_info:
  author: Christer Eriksson
  description: Role for deploying web-dev 
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Fedora
      versions:
        - 31
        - 32
  galaxy_tags:
    - development
dependencies: []

